// Code generated by "stringer -type=Language"; DO NOT EDIT.

package pkg

import "strconv"

const _AcceptedLanguages_name = "ANYJSONYAML"

var _AcceptedLanguages_index = [...]uint8{0, 3, 7, 11}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_AcceptedLanguages_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AcceptedLanguages_name[_AcceptedLanguages_index[i]:_AcceptedLanguages_index[i+1]]
}
